### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Aditya94A** [yeokm1/docs-to-pdf-converter#23]
I'm hesitant to use this as there seem to be several open unsolved issues. Are there any other good alternatives?

**Comment by yeokm1** [comment]
Depends on how you define "dead" 😛 

But more seriously as stated right at the top of my readme: 
`I'm not maintaining this code as I neither have personal resources nor am I still using this project. I'll be happy to oblige if you have any pull requests or even if you wish to be a co-maintainer.`

So far many people have opened issues, but none have volunteered to help so....

The problem with most issues is that the cause is likely due to the upstream libraries that this project relies on. The most one can do is keep the libraries used in this project up to date.

If you do not strictly need the conversion functions to be standalone like this project, you can consider this with Libreoffice. https://github.com/unoconv/unoconv
